# Generated by Django 5.1.4 on 2024-12-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_alter_order_color_alter_order_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='color',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('color', 'size', 'product_name')},
        ),
    ]
