# Generated by Django 5.1.4 on 2024-12-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0004_alter_order_color_alter_order_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.CharField(default=2333, max_length=100),
            preserve_default=False,
        ),
    ]
