# Generated by Django 5.1.4 on 2024-12-18 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0015_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
