# Generated by Django 5.1.4 on 2024-12-18 08:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0017_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('subj', models.CharField(max_length=30)),
                ('msg', models.TextField()),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('color', 'size', 'product_name', 'username')},
        ),
    ]
