# Generated by Django 5.1.4 on 2024-12-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageprocessing',
            name='unique_code',
            field=models.CharField(default=1, max_length=7, unique=True),
            preserve_default=False,
        ),
    ]
