# Generated by Django 5.1.4 on 2024-12-12 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_alter_imageprocessing_unique_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageprocessing',
            name='unique_code',
        ),
    ]
