# Generated by Django 5.1.4 on 2024-12-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_remove_imageprocessing_unique_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageprocessing',
            name='unique_code',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
